name: Deploy Application

on:
  push:
      branches:
        - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Application to Github Pages

    strategy:
      matrix:
        os: [ubuntu-latest]
        bun: [1.2.22]
        # Needed for custom CE fork
        node: [24]

    runs-on: ${{ matrix.os }}

    env:
      VITE_BASE: '/unitree-f2025-sdd-project/'

    permissions:
      contents: read
      pages: write
      id-token: write

    concurrency:
      group: pages
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun }}
      # Needed for custom CE fork
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Install Dependencies
        run: bun i --frozen-lockfile
      # Needed for custom CE fork
      - name: Build Dependencies
        run: bun run build-deps
      - name: Build Resources
        run: bun run --bun build
      - name: Upload Static Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'
      - name: Deploy Site to Github Pages
        id: deploy
        uses: actions/deploy-pages@v4
